# Uncomment this line to define a global platform for your project
# platform :ios, '9.0'

target 'CommonTool' do
  # Uncomment this line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for CommonTool
pod 'AFNetworking'
pod 'YYModel'
pod 'Masonry'
pod 'SDWebImage'
pod 'MJRefresh'
pod 'IMYWebView'
pod 'MBProgressHUD'
end
